### ISSUE TITLE
이런건 lambda@edge로 하셔야죠

### ISSUE THREAD

**Issue by breath103** [pluto-net/url-redirector#1]
단순 redirecting을 lambda에서 하다니.. ㅠㅠ 안될일이죠

**Comment by TylerShin** [comment]
ㅋㅋㅋㅋ 건드려본적도 없어서 예시를 보여주세요 ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by breath103** [comment]
처음 하면 졸라 헤매야 하는거라 걍 보여주기 아까움 ^^

**Comment by TylerShin** [comment]
이건 어차피 버릴 주소라 상관없는데 다음꺼는 람다엣지로 해봐야겠네요.
누가 벌써 플러그인 만들어놨던데 ^^
